### PR TITLE
📝 Add azure status badge

### PR DESCRIPTION
**Pull request by HotelCalifornia**
#### Summary:

Adds a status badge for our Azure pipelines builds to the readme. Also adds a unibeautify config
#### Motivation:

Looks cool.
##### References (optional):

N/A
#### Test Plan:

N/A

### CODE REVIEW

**Review by edjubuh — DISMISSED** [review]
Make it so

**Review by edjubuh — DISMISSED** [review]
Need to update test plan with some verification that unibeautify will lint our code. This could be done by creating a PR with intentionally bad format. Also need to update PR title and description.

**Comment by kunwarsahni01** [comment]
Removed unibeautify config change from this pr.

**Comment by HotelCalifornia** [comment]
linux failure appears to be because of marcelotduarte/cx_Freeze#884

**Review by kunwarsahni01 — APPROVED** [review]

**Pull request merged**
