### PR TITLE
🐛Fixes --run-after flag priority issues.

### LINKED ISSUE #132: Upload's run-after switch does nothing
#### Expected Behavior:
`prosv5 u --run-after` should cause the program to run after the upload completes successfully.

#### Actual Behavior:
`prosv5 u --run-after` uploads the program successfully like normal, but does not run the program after the upload is finished.

#### Steps to reproduce:
This is reproducible every time. Just run `prosv5 u --run-after` and observe it has the same behavior as `prosv5 u --no-run-after`.

#### System information:
Operating System:  Fedora 32

PROS Version: 3.1.4

#### Additional Information
This happens with hot/cold and monolith.

### PR DESCRIPTION
**Pull request by BennyBot**
#### Summary:
Changes logic statements when deciding which vex.V5Device.FTCompleteOptions argument to pass. Essentially gives the --run-after switch priority over the --run-screen switch in the if/elif/else chain.

#### Motivation:
Quality of life feature for users that will allow them to make changes and test them more efficiently. Removes the need to go through the controller menu or press buttons on the brain to test changes.

##### References (optional):
closes #132 

#### Test Plan:
Tested every combination of --run-after and --run-screen switches to verify that new logic works.
The link to a video of the test cases is here: https://drive.google.com/file/d/1mYM6LzFtDHzZ1Jm6cl8S6FvG-k9EKSDa/view?usp=sharing

### CODE REVIEW

**Review by WillXuCodes — DISMISSED** [review]
I think one thing we should do for this, is to add some aliases for some of these options (such as -r for running after uploading, or something along the lines of that). I'm honestly not sure what the best abbreviations would be so anybody can feel free to chime in on this.

**Comment by HotelCalifornia** [comment]
I'd prefer you didn't modify all the flags in this PR... imo the other aliases should go in a separate one

**Comment by HotelCalifornia** [comment]
I also think having both run after and run screen is confusing because they're mutually exclusive in some cases.

| `run_screen` | `run_after` | behaviour |
| ----------------- | ------------- | ------------- |
| T | T | unclear to user |
| T | F | run program post upload |
| F | T | show run screen post upload |
| F | F | show nothing on the brain? |

maybe it would be a cleaner solution to fold these two flag options into one enum option `action`, so that the user can specify which of the three valid actions they want

```
$ pros upload --action=RUN
# run program after uploading

$ pros upload --action=SCREEN
# show screen after uploading (default)

$ pros upload --action=NOTHING
# show nothing and execute nothing after uploading
```

**Review by kunwarsahni01 — APPROVED** [review]
This LGTM, was functioning properly in testing.

**Pull request merged**
