### PR TITLE
🐛Fix issue with invalid directory name check

### PR DESCRIPTION
**Pull request by ghost**
#### Summary:
Removed "\", "/", and ":" characters from check for invalid directory name when creating a project.

#### Motivation:
Preventing these characters from being used caused issues with using absolute file paths when creating a project.

##### References (optional):
Issue #278 is still unresolved

#### Test Plan:
- [ ] Attempt to create a project using an absolute file path (that includes all 3 characters)
image

### CODE REVIEW

**Comment by ayushuk** [comment]
The backslash is still in the check, how were you able to create a project with it in the name? Also we should probably remove it anyways if people want to create project on windows and it does trigger.

**Review by ayushuk — CHANGES_REQUESTED** [review]
Remove the backslash from the check

**Comment by ghost** [comment]
I made that mistake at first too, '\\'' is the single quote character (the backslash is the escape character in this case)

**Review by ayushuk — APPROVED** [review]
LGTM

**Comment by stualden** [comment]
I ran into this problem yesterday (it gagged on the colon, which is a problem if you're working with Windows!).  Will this fix make it into the VSCode extension installation soon?  Sorry for the newbie question - I started to learn PROS just yesterday and this was a big roadblock.

**Comment by ayushuk** [comment]
Hello, thanks for trying out PROS! The bugfix is merged and we are in the process of making the release but are running into some issues. For now, you can use the pros terminal to make new projects using `pros c n [project directory]`. Sorry about the inconvenience.

**Comment by stualden** [comment]
Thank you for all your great work on this project!  And thanks for that tip - so long as `[project directory]` contains no colon or backslash(es), it appears to work just fine, as expected.

**Pull request merged**
