### PR TITLE
🎨Pre commit

### PR DESCRIPTION
**Pull request by mayankpatibandla**
#### Summary:
Adds pre-commit to run some hooks that must pass before a commit is allowed. Some basic errors regarding whitespace and unused variables have been fixed.

#### Motivation:
The goal is to enforce a more consistent coding style and fix linting issues. Currently most errors have been disabled, but we will need to enable some of them later to comply to a chosen standard.

#### Test Plan:
- [x] To set up pre-commit, run `pip install pre-commit` if you don't already have it, and then run `pre-commit install` in the project directory. Pre-commit hooks should now run automatically every time a new commit is made.
- [x] Make sure that `pre-commit run --all-files` passes for all files in the project.

### CODE REVIEW

**Comment by ayushuk** [comment]
From the diff I can't see the difference between this and #301. What was the purpose of this PR again?

**Comment by mayankpatibandla** [comment]
#300 got merged into #301 so that #301 could be tested. You originally said that you wanted me to put them in two separate PRs. Do you still want that or can we get rid of #300?

**Comment by ayushuk** [comment]
Oh right. Yeah I think we can close #300 since I think I was trying to be safe before doing a release. Since we are merging this after a release we should be able to merge everything together since #301 has everything. Feel free to close this PR and lets merge only #301.

**Comment by mayankpatibandla** [comment]
Closed because this PR got merged into #301

**Pull request closed without merging**
